name: PlexServices
version: '3.8'

services:

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - "8686:8686"
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/j/DOCKER/lidarr:/config
    restart: unless-stopped

  kometa:
    image: linuxserver/kometa:latest
    container_name: kometa
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/j/DOCKER/Kometa:/config
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/radarr:/config
    ports:
      - 8282:7878
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    user: node-red
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/node-red/data:/config
    ports:
      - 1880:1880
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest    
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/Jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    
  tautulli:
    image: linuxserver/tautulli:latest
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/tautulli:/config
    ports:
      - 8383:8181
    restart: unless-stopped
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/bazarr:/config
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/j/DOCKER/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    